<?php

/**
 * PluginToken
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginToken extends BaseToken
{
  const STATUS_ACCESS = 0;
  const STATUS_REQUEST = 1;

  public function toOAuthToken()
  {
    return new OAuthToken($this->getTokenKey(), $this->getTokenSecret());
  }
}